package com.autoclicker.test;

import android.app.*;import android.content.*;import android.graphics.*;import android.hardware.display.*;import android.media.*;import android.media.projection.*;import android.os.*;import androidx.annotation.NonNull;import com.google.mlkit.vision.common.InputImage;import com.google.mlkit.vision.text.*;import java.nio.*;import java.util.concurrent.*;

public class ScreenMonitorService extends Service {
    public static boolean running=false; private static ScreenMonitorService self; private MediaProjection projection; private VirtualDisplay display; private ImageReader reader; private ScheduledExecutorService exec; private int trigger=15,delay=22; private boolean armed=true; private Rect region; private Handler main=new Handler(Looper.getMainLooper());
    public static void start(Context c,Intent data,int t,int d){Intent i=new Intent(c,ScreenMonitorService.class);i.putExtra("result",data);i.putExtra("code",Activity.RESULT_OK);i.putExtra("trigger",t);i.putExtra("delay",d);c.startForegroundService(i);}
    public static void stop(Context c){try{c.stopService(new Intent(c,ScreenMonitorService.class));}catch(Exception ignored){}}
    public static void pause(){if(self!=null)self.running=false;} public static void resume(){if(self!=null)self.running=true;}
    @Override public void onCreate(){super.onCreate();self=this; createChannel(); startForeground(7,new Notification.Builder(this,"auto").setContentTitle("Auto Clicker Test").setContentText("Screen monitoring is active").setSmallIcon(android.R.drawable.ic_media_play).build());}
    @Override public int onStartCommand(Intent in,int flags,int id){Intent data=in.getParcelableExtra("result");trigger=in.getIntExtra("trigger",15);delay=in.getIntExtra("delay",22);if(data!=null)setupCapture(data,in.getIntExtra("code",Activity.RESULT_OK));return START_NOT_STICKY;}
    private void setupCapture(Intent data,int code){if(projection!=null)return; MediaProjectionManager m=(MediaProjectionManager)getSystemService(MEDIA_PROJECTION_SERVICE);projection=m.getMediaProjection(code,data);DisplayMetrics dm=getResources().getDisplayMetrics();int w=dm.widthPixels,h=dm.heightPixels;reader=ImageReader.newInstance(w,h,PixelFormat.RGBA_8888,2);display=projection.createVirtualDisplay("AutoClickerCapture",w,h,dm.densityDpi,DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR,reader.getSurface(),null,main);region=AutomationAccessibilityService.instance==null?new Rect(0,0,w,h):AutomationAccessibilityService.instance.getRegion();running=true;exec=Executors.newSingleThreadScheduledExecutor();exec.scheduleAtFixedRate(this::capture,0,500,TimeUnit.MILLISECONDS);}
    private void capture(){if(!running||reader==null)return;Image im=null;try{im=reader.acquireLatestImage();if(im==null)return;Bitmap b=imageToBitmap(im);Rect r=region==null?new Rect(0,0,b.getWidth(),b.getHeight()):new Rect(Math.max(0,region.left),Math.max(0,region.top),Math.min(b.getWidth(),region.right),Math.min(b.getHeight(),region.bottom));if(r.width()<=0||r.height()<=0)return;Bitmap crop=Bitmap.createBitmap(b,r.left,r.top,r.width(),r.height());TextRecognizer rec=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);rec.process(InputImage.fromBitmap(crop,0)).addOnSuccessListener(res->{String text=res.getText().replaceAll("\\s+","");if(text.contains(String.valueOf(trigger))){if(armed){armed=false;doFirstClick();}}else{armed=true;}}).addOnCompleteListener(x->{rec.close();crop.recycle();b.recycle();});}catch(Exception ignored){}finally{if(im!=null)im.close();}}
    private void doFirstClick(){if(AutomationAccessibilityService.instance==null)return;AutomationAccessibilityService.instance.clickTarget();new Handler(Looper.getMainLooper()).postDelayed(()->{if(AutomationAccessibilityService.instance!=null&&running)AutomationAccessibilityService.instance.clickTarget();},delay*1000L);}
    private Bitmap imageToBitmap(Image image){Image.Plane p=image.getPlanes()[0];ByteBuffer buf=p.getBuffer();int pixelStride=p.getPixelStride(),rowStride=p.getRowStride();int rowPadding=rowStride-pixelStride*image.getWidth();Bitmap bmp=Bitmap.createBitmap(image.getWidth()+rowPadding/pixelStride,image.getHeight(),Bitmap.Config.ARGB_8888);buf.rewind();bmp.copyPixelsFromBuffer(buf);return Bitmap.createBitmap(bmp,0,0,image.getWidth(),image.getHeight());}
    private void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel("auto","Auto Clicker",NotificationManager.IMPORTANCE_LOW);getSystemService(NotificationManager.class).createNotificationChannel(c);}}
    @Override public void onDestroy(){running=false;if(exec!=null)exec.shutdownNow();if(display!=null)display.release();if(reader!=null)reader.close();if(projection!=null)projection.stop();self=null;super.onDestroy();}
    @Override public android.os.IBinder onBind(Intent i){return null;}
}
